version: '3.8'

services:
  ingesta-pets:
    build: ./ingesta-pets
    container_name: robot-pets
    network_mode: "host"

  ingesta-treatments:
    build: ./ingesta-treatments
    container_name: robot-treatments
    network_mode: "host"

  ingesta-appointments:
    build: ./ingesta-appointments
    container_name: robot-appointments
    network_mode: "host"
